### ISSUE TITLE
Empty CSV file

### ISSUE THREAD

**Issue by wesbeyrent** [HamletDuFromage/nx-titles-list-dumper#1]
The app is dumping an empty CSV file.  On AMS 1.1.1, System 13.0.0

[titles.csv](https://github.com/HamletDuFromage/nx-titles-list-dumper/files/7404078/titles.csv)

**Comment by HamletDuFromage** [comment]
I "fixed" a bug but didn't try it, so it's entirely possible. You can use the second to last release that should work fine and I'll get on it as soon as possible

**Comment by wesbeyrent** [comment]
I tried all 3 releases and got a good CSV out of one of them. Thanks!

BTW, I have all 3 releases installed with different filenames and 1.0.1 and 1.0.2 both show as 1.0.1 in the HB launcher for me.

**Comment by HamletDuFromage** [comment]
Ah right, forgot to change the version string in the makefile too. I'll just nuke the release for now. Thanks for letting me know

**Comment by wesbeyrent** [comment]
Thanks for the quick fix! Is the .nro on its way? Happy compile myself, but not experienced doing it. 😀

**Comment by HamletDuFromage** [comment]
The upload failed but it's there now. Sorry about that

**Comment by wesbeyrent** [comment]
Works perfectly. Thanks for everything! Nice work all around!
